<#
.SYNOPSIS
    Cleans up common temporary build and cache directories for Python projects.

.DESCRIPTION
    This script finds and removes various temporary files and directories
    that are commonly generated by Python development, including:
    - __pycache__ directories
    - build directory
    - dist directory
    - .pytest_cache directory
    - egg-info directories (e.g., mxtools.egg-info)

    It first identifies all the targets to be removed, then iterates through
    them, and if they exist, removes them with a confirmation message.
    It provides colored output to indicate success or failure.

.NOTES
    Author: Ash Hellwig <ahellwig.dev@gmail.com>
    Version: 1.0
    Date: 2025-09-22
#>

# Function to get the list of directories to clean.
function Get-PyCacheTargets {
    # Find all __pycache__ directories up to a depth of 3.
    # The 'Get-ChildItem -Recurse -Depth 3' is the PowerShell equivalent
    # of 'find . -maxdepth 3'.
    # We use a filter to match the __pycache__ directories.
    $pycaches = `
        Get-ChildItem `
        -Path . `
        -Recurse `
        -Depth 3 `
        -Directory `
        -Filter "__pycache__" `
        -ErrorAction SilentlyContinue | `
        Select-Object `
        -ExpandProperty FullName

    # A fixed list of additional directories to remove.
    $additionalTargets = @(
        ".\build",
        ".\dist",
        ".\mxtools.egg-info",
        ".\.pytest_cache",
        ".\.venv\Lib\site-packages\mxtools-0.0.1.dist-info"
    )

    # Combine the found caches with the fixed list and return the array.
    return $pycaches + $additionalTargets
}

# Get the list of items to remove.
$itemsToRemove = Get-PyCacheTargets

# Check if any items were found.
if ($itemsToRemove.Count -eq 0) {
    Write-Host "No Python cache or build directories found to remove." -ForegroundColor Yellow
    return
}

Write-Host "Found $($itemsToRemove.Count) items to remove. " -ForegroundColor Cyan

# Iterate through each item and remove it.
foreach ($item in $itemsToRemove) {
    # Check if the item actually exists before attempting to remove it.
    if (Test-Path -Path $item) {
        Write-Host "Removing $item..." -ForegroundColor Red

        # Use -Recurse to remove directories and their contents.
        # Use -Force to remove read-only files if necessary.
        # Use -ErrorAction SilentlyContinue to prevent the script from stopping
        # if a file cannot be removed.
        Remove-Item -Path $item -Recurse -Force -ErrorAction SilentlyContinue

        # Verify if the item was successfully removed.
        if (-not (Test-Path -Path $item)) {
            Write-Host "$item Removed." -ForegroundColor Green
        }
        else {
            Write-Host "Failed to remove $item." -ForegroundColor Yellow
        }
    }
}
